
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FM_SupplierPaymentHistory extends javax.swing.JFrame {
    private PO [] supplierPaymentHistory;
    private User authenticatedUser;
    private DefaultTableModel tableModel = new DefaultTableModel();
    
    /**
     * Creates new form FM_SupplierPaymentHistory
     * @param authenticatedUser
     * @param supplier
     */
    public FM_SupplierPaymentHistory(User authenticatedUser, Supplier supplier) {
        initComponents();
        supplierIDLabel.setText(supplier.getSupplierId());
        supplierNameLabel.setText(supplier.getName());
        supplierEmailLabel.setText(supplier.getEmail());
        
        this.authenticatedUser = authenticatedUser;
        
        supplierPaymentHistory = supplier.getSupplierPaymentHistory();
        setTable(supplier.getSupplierId());
    }
    
    private void setTable(String supplierId){
        String[] columnNames = {"Item ID", "Item Name", "PO ID", "Reorder amount", "PO Created Date", "Payment Status"};
        tableModel.setColumnIdentifiers(columnNames);
        
        for (PO payment : supplierPaymentHistory){
            if (payment != null){
                String poId = payment.getPoId();
                String createdDate = payment.getTimestamp();
                String status = payment.getStatus();

                //Loop items in PO
                Item [] poItems = payment.getPOItems();
                for (Item poItem : poItems){
                    if (poItem != null && poItem.getSupplier().getSupplierId().equals(supplierId)){
                        String itemId = poItem.getItemId();
                        String itemName = poItem.getItemName();
                        String reorderAmt = poItem.getReorderAmt() + "";

                        String [] tableRow = {itemId, itemName, poId, reorderAmt, createdDate, status};
                        tableModel.addRow(tableRow);
                    }
                }
            }
        }
        
        paymentHistoryTable.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        paymentHistoryTable = new javax.swing.JTable();
        POCheckBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        supplierIDLabel = new javax.swing.JLabel();
        supplierNameLabel = new javax.swing.JLabel();
        supplierEmailLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Payment History");

        jLabel2.setText("Supplier ID:");

        jLabel3.setText("Supplier Name:");

        jLabel4.setText("Supplier Email:");

        paymentHistoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane1.setViewportView(paymentHistoryTable);

        POCheckBtn.setText("Check PO");
        POCheckBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                POCheckBtnActionPerformed(evt);
            }
        });

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        supplierIDLabel.setText("jLabel5");

        supplierNameLabel.setText("jLabel5");

        supplierEmailLabel.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(supplierIDLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                                    .addComponent(supplierNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(supplierEmailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(POCheckBtn)
                                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(supplierIDLabel)
                    .addComponent(POCheckBtn))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(supplierNameLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(backBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(supplierEmailLabel))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void POCheckBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_POCheckBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = paymentHistoryTable.getSelectedRow();
        
        // Ensure a row is selected
        if (selectedRow != -1) {
            String poId = tableModel.getValueAt(selectedRow, 2).toString();
            PO targetPO = PO.getPOById(poId);
            
            FM_PoItems poItems = new FM_PoItems(authenticatedUser, targetPO);
            poItems.setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Please select a row.");
        }
    }//GEN-LAST:event_POCheckBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        FM_SupplierList fmSupplierList = new FM_SupplierList(authenticatedUser);
        fmSupplierList.setVisible(true);
        dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton POCheckBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable paymentHistoryTable;
    private javax.swing.JLabel supplierEmailLabel;
    private javax.swing.JLabel supplierIDLabel;
    private javax.swing.JLabel supplierNameLabel;
    // End of variables declaration//GEN-END:variables
}
